### ISSUE TITLE
FormAssembly Developer Hub Styling Appears Broken

### ISSUE THREAD

**Issue by qualeo** [veerwest/formassembly-api#18]
> _"For the Developer Sandbox and FormAssembly.com, you must register through the [FormAssembly Developer Hub](http://www3.formassembly.com/api/)."_

**Clicking the link above (https://www3.formassembly.com/api/) renders the following page:**

![screencapture-www3-formassembly-api-2022-04-22-14_47_12](https://user-images.githubusercontent.com/103188142/164776178-a5424f36-76bf-4bfe-9c3f-71dcc3e12a1c.png)

**Chrome Developer Tools Console Shows the Following:**

![Screenshot from 2022-04-22 14-47-53](https://user-images.githubusercontent.com/103188142/164776208-3eefeb3f-1ec0-4667-a3dd-823601fdc399.png)

**Comment by edasque** [comment]
Fixed in https://github.com/veerwest/formassembly-api/pull/19 , thank you
